import type {
  Difficulty,
  Equipment,
  ExerciseCategory,
  ProgressionMode,
  Unit,
  WorkoutGoal,
} from "@/lib/domain/types";

/**
 * Seed content for Uruz: the exercise library, workout templates, and badges.
 *
 * Exercises are DATA, not code (spec §4/§5) so the library can grow without
 * deploys. Content is Danish; the seven core exercises reproduce Kristian &
 * Ib's actual start program (spec §15). `svgKey` points at a stick-figure
 * illustration in `@/components/exercise/illustrations`.
 */

export interface SeedExercise {
  slug: string;
  nameDa: string;
  nameEn: string;
  category: ExerciseCategory;
  primaryMuscles: string[];
  equipment: Equipment;
  unit: Unit;
  isBodyweight: boolean;
  instructionsSteps: string[];
  instructionsStepsEn: string[];
  cues: string[];
  cuesEn: string[];
  saferVariant: string | null;
  saferVariantEn: string | null;
  svgKey: string;
  difficulty: Difficulty;
}

export const SEED_EXERCISES: SeedExercise[] = [
  {
    slug: "benpres",
    nameDa: "Benpres (maskine)",
    nameEn: "Leg press (machine)",
    category: "ben",
    primaryMuscles: ["forlaar", "balder", "baglaar"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Sæt dig godt tilbage i sædet med hele ryggen støttet.",
      "Placér fødderne skulderbredt midt på pladen.",
      "Skub pladen roligt væk til benene er næsten strakte — lås ikke knæene.",
      "Sænk kontrolleret tilbage til knæene er ca. 90 grader.",
    ],
    instructionsStepsEn: [
      "Sit well back in the seat with your whole back supported.",
      "Place your feet shoulder-width apart in the middle of the plate.",
      "Push the plate away calmly until your legs are almost straight — don't lock your knees.",
      "Lower under control until your knees are at about 90 degrees.",
    ],
    cues: ["Hælene i pladen", "Knæ følger tæernes retning", "Rolig kontrol ned"],
    cuesEn: [
      "Heels into the plate",
      "Knees track over your toes",
      "Slow and controlled on the way down",
    ],
    saferVariant: "Kortere bevægebane og lavere vægt hvis knæene generer.",
    saferVariantEn: "Shorter range of motion and lighter weight if your knees complain.",
    svgKey: "benpres",
    difficulty: "begynder",
  },
  {
    slug: "brystpres",
    nameDa: "Brystpres (maskine)",
    nameEn: "Chest press (machine)",
    category: "pres",
    primaryMuscles: ["bryst", "skuldre", "triceps"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Justér sædet så håndtagene er i højde med midten af brystet.",
      "Hold skuldrene nede og bagud mod ryglænet.",
      "Skub håndtagene frem til armene er næsten strakte.",
      "Før roligt tilbage til du mærker et let stræk over brystet.",
    ],
    instructionsStepsEn: [
      "Adjust the seat so the handles are level with the middle of your chest.",
      "Keep your shoulders down and back against the backrest.",
      "Push the handles forward until your arms are almost straight.",
      "Return calmly until you feel a light stretch across the chest.",
    ],
    cues: ["Skulderblade samlet", "Pust ud når du presser", "Ingen låste albuer"],
    cuesEn: [
      "Shoulder blades together",
      "Breathe out as you press",
      "No locked elbows",
    ],
    saferVariant: "Reducér vægt og bevægebane hvis skulderen gør ondt.",
    saferVariantEn: "Reduce the weight and range of motion if your shoulder hurts.",
    svgKey: "brystpres",
    difficulty: "begynder",
  },
  {
    slug: "siddende-roning",
    nameDa: "Siddende roning (kabel)",
    nameEn: "Seated row (cable)",
    category: "traek",
    primaryMuscles: ["ryg", "biceps", "skuldre"],
    equipment: "kabel",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Sæt dig med let bøjede knæ og ret ryg.",
      "Grib håndtaget og træk skulderbladene sammen.",
      "Træk håndtaget ind mod maven, albuerne tæt på kroppen.",
      "Før roligt frem igen med kontrol — undgå at runde ryggen.",
    ],
    instructionsStepsEn: [
      "Sit with slightly bent knees and a straight back.",
      "Grab the handle and draw your shoulder blades together.",
      "Pull the handle in toward your stomach, elbows close to your body.",
      "Return forward under control — avoid rounding your back.",
    ],
    cues: ["Træk med albuerne", "Bryst frem", "Ret ryg hele vejen"],
    cuesEn: [
      "Pull with your elbows",
      "Chest forward",
      "Straight back throughout",
    ],
    saferVariant: "Let vægt og fokus på teknik hvis lænden er øm.",
    saferVariantEn: "Light weight and a focus on technique if your lower back is sore.",
    svgKey: "roning",
    difficulty: "begynder",
  },
  {
    slug: "nedtraek",
    nameDa: "Nedtræk / lat pulldown",
    nameEn: "Lat pulldown",
    category: "traek",
    primaryMuscles: ["ryg", "biceps"],
    equipment: "kabel",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Grib stangen lidt bredere end skulderbredde.",
      "Sæt lårene fast under puderne.",
      "Træk stangen ned mod øvre bryst mens du fører albuerne ned.",
      "Før roligt op igen til armene er strakte.",
    ],
    instructionsStepsEn: [
      "Grip the bar slightly wider than shoulder-width.",
      "Lock your thighs under the pads.",
      "Pull the bar down toward your upper chest as you drive your elbows down.",
      "Return calmly until your arms are straight.",
    ],
    cues: ["Albuer ned og tilbage", "Bryst op mod stangen", "Ingen gynge i kroppen"],
    cuesEn: [
      "Elbows down and back",
      "Chest up toward the bar",
      "No swinging",
    ],
    saferVariant: "Brug lettere vægt og assisteret variant ved skulderbesvær.",
    saferVariantEn: "Use a lighter weight or an assisted variation if your shoulders bother you.",
    svgKey: "nedtraek",
    difficulty: "begynder",
  },
  {
    slug: "skulderpres",
    nameDa: "Skulderpres (maskine)",
    nameEn: "Shoulder press (machine)",
    category: "pres",
    primaryMuscles: ["skuldre", "triceps"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Justér sædet så håndtagene starter ved skulderhøjde.",
      "Hold ryggen mod ryglænet og maven let spændt.",
      "Pres håndtagene op til armene er næsten strakte.",
      "Sænk roligt tilbage til skulderhøjde.",
    ],
    instructionsStepsEn: [
      "Adjust the seat so the handles start at shoulder height.",
      "Keep your back against the backrest and your core lightly braced.",
      "Press the handles up until your arms are almost straight.",
      "Lower calmly back to shoulder height.",
    ],
    cues: ["Spænd maven", "Pres lige op", "Undgå at låse albuerne"],
    cuesEn: [
      "Brace your core",
      "Press straight up",
      "Avoid locking your elbows",
    ],
    saferVariant: "Neutralt greb og lav vægt hvis skulderen er sart.",
    saferVariantEn: "Neutral grip and low weight if your shoulder is sensitive.",
    svgKey: "skulderpres",
    difficulty: "begynder",
  },
  {
    slug: "leg-curl",
    nameDa: "Baglårsbøj / leg curl (maskine)",
    nameEn: "Leg curl (machine)",
    category: "ben",
    primaryMuscles: ["baglaar"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Placér dig så knæene flugter med maskinens omdrejningspunkt.",
      "Læg anklerne over puden.",
      "Bøj benene og træk hælene mod bagdelen.",
      "Sænk roligt tilbage med kontrol.",
    ],
    instructionsStepsEn: [
      "Position yourself so your knees line up with the machine's pivot.",
      "Place your ankles over the pad.",
      "Bend your legs and pull your heels toward your seat.",
      "Lower back calmly under control.",
    ],
    cues: ["Rolig excentrisk fase", "Hoften bliver i sædet", "Fuld bevægebane"],
    cuesEn: [
      "Slow on the lowering phase",
      "Hips stay in the seat",
      "Full range of motion",
    ],
    saferVariant: "Mindre bevægebane hvis baglåret krammer.",
    saferVariantEn: "Reduce the range of motion if your hamstring cramps.",
    svgKey: "legcurl",
    difficulty: "begynder",
  },
  {
    slug: "planke",
    nameDa: "Planke",
    nameEn: "Plank",
    category: "kerne",
    primaryMuscles: ["mave", "kerne"],
    equipment: "kropsvaegt",
    unit: "sek",
    isBodyweight: true,
    instructionsSteps: [
      "Støt på underarme og tæer.",
      "Hold kroppen som en lige linje fra hoved til hæl.",
      "Spænd mave og balder, træk navlen let ind.",
      "Hold positionen og træk vejret roligt.",
    ],
    instructionsStepsEn: [
      "Support yourself on your forearms and toes.",
      "Hold your body in a straight line from head to heel.",
      "Brace your abs and glutes, drawing your navel in slightly.",
      "Hold the position and breathe calmly.",
    ],
    cues: ["Lige linje — ingen sænket hofte", "Spænd balderne", "Se ned i gulvet"],
    cuesEn: [
      "Straight line — no sagging hips",
      "Squeeze your glutes",
      "Look down at the floor",
    ],
    saferVariant: "Planke på knæene hvis lænden synker.",
    saferVariantEn: "Plank from your knees if your lower back sags.",
    svgKey: "planke",
    difficulty: "begynder",
  },
  // ---- Broader library (spec §15: "gør biblioteket rigt fra start") ----
  {
    slug: "goblet-squat",
    nameDa: "Goblet squat (håndvægt)",
    nameEn: "Goblet squat (dumbbell)",
    category: "ben",
    primaryMuscles: ["forlaar", "balder"],
    equipment: "haandvaegt",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Hold én håndvægt lodret ind mod brystet.",
      "Stå skulderbredt med tæerne let udad.",
      "Sæt dig ned i knæ og hofte til lårene er vandrette.",
      "Rejs dig igen ved at skubbe fra hælene.",
    ],
    instructionsStepsEn: [
      "Hold one dumbbell vertically against your chest.",
      "Stand shoulder-width apart with toes turned slightly out.",
      "Sit down through knees and hips until your thighs are horizontal.",
      "Stand back up by pushing through your heels.",
    ],
    cues: ["Albuer inde ved kroppen", "Bryst op", "Knæ ud over tæer"],
    cuesEn: [
      "Elbows tucked in",
      "Chest up",
      "Knees out over your toes",
    ],
    saferVariant: "Squat til en bænk hvis dybden er svær.",
    saferVariantEn: "Squat down to a bench if the depth is difficult.",
    svgKey: "squat",
    difficulty: "erfaren",
  },
  {
    slug: "rumaensk-markloeft-maskine",
    nameDa: "Rumænsk markløft (maskine)",
    nameEn: "Romanian deadlift (machine)",
    category: "ben",
    primaryMuscles: ["baglaar", "balder", "ryg"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Stå med let bøjede knæ og ret ryg.",
      "Før hoften bagud og sænk vægten langs benene.",
      "Stop når du mærker stræk i baglåret.",
      "Pres hoften frem og rejs dig igen.",
    ],
    instructionsStepsEn: [
      "Stand with slightly bent knees and a straight back.",
      "Push your hips back and lower the weight along your legs.",
      "Stop when you feel a stretch in your hamstrings.",
      "Drive your hips forward and stand back up.",
    ],
    cues: ["Hoften bagud", "Ret ryg", "Vægten tæt på kroppen"],
    cuesEn: [
      "Hips back",
      "Straight back",
      "Keep the weight close to your body",
    ],
    saferVariant: "Kortere bevægebane ved lændegener.",
    saferVariantEn: "Shorter range of motion if your lower back complains.",
    svgKey: "rdl",
    difficulty: "erfaren",
  },
  {
    slug: "biceps-curl",
    nameDa: "Biceps curl (håndvægt)",
    nameEn: "Biceps curl (dumbbell)",
    category: "traek",
    primaryMuscles: ["biceps"],
    equipment: "haandvaegt",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Stå med en håndvægt i hver hånd, armene langs siden.",
      "Bøj albuerne og løft vægtene mod skuldrene.",
      "Hold albuerne tæt på kroppen.",
      "Sænk roligt tilbage til strakte arme.",
    ],
    instructionsStepsEn: [
      "Stand with a dumbbell in each hand, arms at your sides.",
      "Bend your elbows and lift the weights toward your shoulders.",
      "Keep your elbows close to your body.",
      "Lower calmly back to straight arms.",
    ],
    cues: ["Albuer i ro", "Ingen sving i kroppen", "Fuld kontrol ned"],
    cuesEn: [
      "Elbows still",
      "No swinging the body",
      "Full control on the way down",
    ],
    saferVariant: "Lettere vægt hvis albuen generer.",
    saferVariantEn: "Lighter weight if your elbow bothers you.",
    svgKey: "curl",
    difficulty: "begynder",
  },
  {
    slug: "triceps-pushdown",
    nameDa: "Triceps pushdown (kabel)",
    nameEn: "Triceps pushdown (cable)",
    category: "pres",
    primaryMuscles: ["triceps"],
    equipment: "kabel",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Grib stangen i skulderbredde ved en høj kabel.",
      "Hold albuerne tæt ind til kroppen.",
      "Pres stangen ned til armene er strakte.",
      "Før roligt op igen uden at albuerne vandrer.",
    ],
    instructionsStepsEn: [
      "Grip the bar at shoulder-width on a high cable.",
      "Keep your elbows tight to your body.",
      "Press the bar down until your arms are straight.",
      "Return calmly without letting your elbows drift.",
    ],
    cues: ["Albuer låst ved siden", "Stræk helt ud", "Rolig retur"],
    cuesEn: [
      "Elbows locked at your sides",
      "Extend fully",
      "Slow return",
    ],
    saferVariant: "Reb i stedet for stang ved albuegener.",
    saferVariantEn: "Use a rope instead of a bar if your elbows bother you.",
    svgKey: "pushdown",
    difficulty: "begynder",
  },
  {
    slug: "mavehaevninger",
    nameDa: "Mavehævninger (crunch)",
    nameEn: "Crunches",
    category: "kerne",
    primaryMuscles: ["mave"],
    equipment: "kropsvaegt",
    unit: "reps",
    isBodyweight: true,
    instructionsSteps: [
      "Lig på ryggen med bøjede knæ.",
      "Læg hænderne ved tindingerne eller over brystet.",
      "Krøl overkroppen op mod knæene.",
      "Sænk roligt tilbage uden at slippe spændingen.",
    ],
    instructionsStepsEn: [
      "Lie on your back with your knees bent.",
      "Place your hands at your temples or across your chest.",
      "Curl your upper body up toward your knees.",
      "Lower calmly without releasing the tension.",
    ],
    cues: ["Hagen fra brystet", "Rolig kontrol", "Træk navlen ind"],
    cuesEn: [
      "Chin off your chest",
      "Slow and controlled",
      "Draw your navel in",
    ],
    saferVariant: "Mindre bevægebane ved nakkegener.",
    saferVariantEn: "Reduce the range of motion if your neck bothers you.",
    svgKey: "crunch",
    difficulty: "begynder",
  },
  {
    slug: "kondi-romaskine",
    nameDa: "Romaskine (kondi)",
    nameEn: "Rowing machine (cardio)",
    category: "kondi",
    primaryMuscles: ["ryg", "ben", "kondi"],
    equipment: "maskine",
    unit: "km",
    isBodyweight: false,
    instructionsSteps: [
      "Sæt fødderne fast i remmene.",
      "Skub fra med benene først.",
      "Træk håndtaget ind mod maven til sidst.",
      "Vend bevægelsen roligt: arme, derefter ben.",
    ],
    instructionsStepsEn: [
      "Strap your feet in securely.",
      "Drive with your legs first.",
      "Pull the handle in toward your stomach last.",
      "Reverse the movement calmly: arms, then legs.",
    ],
    cues: ["Ben — krop — arme", "Ret ryg", "Rolig rytme"],
    cuesEn: [
      "Legs — body — arms",
      "Straight back",
      "Calm rhythm",
    ],
    saferVariant: "Lavere modstand og tempo ved lændegener.",
    saferVariantEn: "Lower resistance and pace if your lower back bothers you.",
    svgKey: "row-machine",
    difficulty: "begynder",
  },
  {
    slug: "kondi-kondicykel",
    nameDa: "Kondicykel (kondi)",
    nameEn: "Stationary bike (cardio)",
    category: "kondi",
    primaryMuscles: ["ben", "kondi"],
    equipment: "maskine",
    unit: "km",
    isBodyweight: false,
    instructionsSteps: [
      "Justér sadelhøjden så knæet er let bøjet i bunden.",
      "Vælg en modstand du kan holde jævnt.",
      "Træd i en rolig, stabil rytme.",
      "Hold en oprejst, afslappet overkrop.",
    ],
    instructionsStepsEn: [
      "Adjust the saddle height so your knee is slightly bent at the bottom.",
      "Pick a resistance you can hold steadily.",
      "Pedal at a calm, stable rhythm.",
      "Keep your upper body upright and relaxed.",
    ],
    cues: ["Jævn kadence", "Skuldre afslappede", "Træk vejret roligt"],
    cuesEn: [
      "Steady cadence",
      "Relaxed shoulders",
      "Breathe calmly",
    ],
    saferVariant: "Lavere modstand ved knægener.",
    saferVariantEn: "Lower the resistance if your knees bother you.",
    svgKey: "bike",
    difficulty: "begynder",
  },
  // ---- Maskinerne der manglede (2026-09-08: "Vi mangler nogle maskiner. Fx. Pec Fly") ----
  {
    slug: "pec-fly",
    nameDa: "Pec fly / butterfly (maskine)",
    nameEn: "Pec fly (machine)",
    category: "pres",
    primaryMuscles: ["bryst", "skuldre"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Justér sædet så håndtagene er i højde med midten af brystet.",
      "Hold ryggen mod ryglænet og albuerne let bøjede hele vejen.",
      "Før armene sammen foran brystet i en rolig bue.",
      "Åbn kontrolleret til du mærker et let stræk over brystet — ikke længere.",
    ],
    instructionsStepsEn: [
      "Adjust the seat so the handles are level with the middle of your chest.",
      "Keep your back against the backrest and your elbows slightly bent throughout.",
      "Bring your arms together in front of your chest in a calm arc.",
      "Open under control until you feel a light stretch across the chest — no further.",
    ],
    cues: ["Klem brystet sammen i midten", "Albuerne bliver let bøjede", "Skuldrene nede"],
    cuesEn: ["Squeeze the chest at the middle", "Elbows stay slightly bent", "Shoulders down"],
    saferVariant: "Kortere bevægebane og lavere vægt hvis skulderen strammer i yderstillingen.",
    saferVariantEn: "Shorter range of motion and less weight if the shoulder pinches at the stretch.",
    svgKey: "pecfly",
    difficulty: "begynder",
  },
  {
    slug: "reverse-fly",
    nameDa: "Omvendt fly / reverse fly (maskine)",
    nameEn: "Reverse fly (machine)",
    category: "traek",
    primaryMuscles: ["skuldre", "ryg"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Sæt dig med brystet mod puden og grib håndtagene foran dig.",
      "Hold armene let bøjede og skuldrene nede.",
      "Før armene ud til siderne og bagud til de er på linje med kroppen.",
      "Før roligt tilbage uden at slippe spændingen mellem skulderbladene.",
    ],
    instructionsStepsEn: [
      "Sit with your chest against the pad and grab the handles in front of you.",
      "Keep your arms slightly bent and your shoulders down.",
      "Sweep your arms out to the sides and back until they line up with your body.",
      "Return calmly without letting go of the tension between the shoulder blades.",
    ],
    cues: ["Klem skulderbladene sammen", "Ingen sving", "Hovedet i ro"],
    cuesEn: ["Squeeze the shoulder blades together", "No swinging", "Head still"],
    saferVariant: "Let vægt — det er en lille muskelgruppe, og den snyder gerne med nakken.",
    saferVariantEn: "Go light — it is a small muscle group, and the neck likes to help.",
    svgKey: "reversefly",
    difficulty: "begynder",
  },
  {
    slug: "skraa-brystpres",
    nameDa: "Skrå brystpres (maskine)",
    nameEn: "Incline chest press (machine)",
    category: "pres",
    primaryMuscles: ["bryst", "skuldre", "triceps"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Justér sædet så håndtagene starter lige under skulderhøjde.",
      "Hold skuldrene nede og bagud mod ryglænet.",
      "Pres håndtagene op og frem til armene er næsten strakte.",
      "Sænk roligt tilbage til du mærker et let stræk øverst i brystet.",
    ],
    instructionsStepsEn: [
      "Adjust the seat so the handles start just below shoulder height.",
      "Keep your shoulders down and back against the backrest.",
      "Press the handles up and forward until your arms are almost straight.",
      "Lower calmly until you feel a light stretch in the upper chest.",
    ],
    cues: ["Skulderblade samlet", "Pres skråt op, ikke lige ud", "Ingen låste albuer"],
    cuesEn: ["Shoulder blades together", "Press up at the angle, not straight out", "No locked elbows"],
    saferVariant: "Neutralt greb og lavere vægt hvis skulderen gør ondt.",
    saferVariantEn: "Neutral grip and less weight if your shoulder hurts.",
    svgKey: "incline",
    difficulty: "begynder",
  },
  {
    slug: "roning-maskine",
    nameDa: "Roning med brystpude (maskine)",
    nameEn: "Chest-supported row (machine)",
    category: "traek",
    primaryMuscles: ["ryg", "biceps"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Justér sædet så brystet hviler på puden og håndtagene er i højde med maven.",
      "Grib håndtagene og lad skulderbladene glide frem.",
      "Træk håndtagene ind mod kroppen med albuerne tæt på siden.",
      "Før roligt frem igen til armene er strakte.",
    ],
    instructionsStepsEn: [
      "Adjust the seat so your chest rests on the pad and the handles are level with your stomach.",
      "Grab the handles and let your shoulder blades slide forward.",
      "Pull the handles in toward your body with your elbows close to your sides.",
      "Return calmly until your arms are straight.",
    ],
    cues: ["Brystet bliver på puden", "Træk med albuerne", "Klem i bunden"],
    cuesEn: ["Chest stays on the pad", "Pull with your elbows", "Squeeze at the end"],
    saferVariant: "Puden bærer lænden, så det er det trygge valg hvis siddende roning generer ryggen.",
    saferVariantEn: "The pad carries your lower back, so this is the safe choice if the seated row bothers it.",
    svgKey: "machinerow",
    difficulty: "begynder",
  },
  {
    slug: "sideloeft-maskine",
    nameDa: "Sideløft (maskine)",
    nameEn: "Lateral raise (machine)",
    category: "pres",
    primaryMuscles: ["skuldre"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Justér sædet så skuldrene flugter med maskinens omdrejningspunkt.",
      "Læg underarmene mod puderne med albuerne let bøjede.",
      "Løft albuerne ud til siden til de er i skulderhøjde.",
      "Sænk roligt tilbage uden at lade vægten falde.",
    ],
    instructionsStepsEn: [
      "Adjust the seat so your shoulders line up with the machine's pivot.",
      "Rest your forearms against the pads with your elbows slightly bent.",
      "Lift your elbows out to the side until they reach shoulder height.",
      "Lower calmly without letting the weight drop.",
    ],
    cues: ["Løft med albuerne", "Stop i skulderhøjde", "Skuldrene væk fra ørerne"],
    cuesEn: ["Lead with your elbows", "Stop at shoulder height", "Shoulders away from your ears"],
    saferVariant: "Kortere bevægebane hvis skulderen klemmer i toppen.",
    saferVariantEn: "Shorter range of motion if the shoulder pinches at the top.",
    svgKey: "lateral",
    difficulty: "begynder",
  },
  {
    slug: "leg-extension",
    nameDa: "Benstræk / leg extension (maskine)",
    nameEn: "Leg extension (machine)",
    category: "ben",
    primaryMuscles: ["forlaar"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Sæt dig så knæene flugter med maskinens omdrejningspunkt.",
      "Læg anklerne bag puden og hold fast i håndtagene.",
      "Stræk benene roligt til de er næsten lige.",
      "Sænk kontrolleret tilbage — lad ikke vægten falde.",
    ],
    instructionsStepsEn: [
      "Sit so your knees line up with the machine's pivot.",
      "Place your ankles behind the pad and hold the handles.",
      "Extend your legs calmly until they are almost straight.",
      "Lower under control — do not let the weight drop.",
    ],
    cues: ["Hold et øjeblik i toppen", "Rolig ned", "Ryggen mod sædet"],
    cuesEn: ["Pause a moment at the top", "Slow on the way down", "Back against the seat"],
    saferVariant: "Kortere bevægebane og lavere vægt hvis knæene generer.",
    saferVariantEn: "Shorter range of motion and less weight if your knees complain.",
    svgKey: "legext",
    difficulty: "begynder",
  },
  {
    slug: "hack-squat",
    nameDa: "Hack squat (maskine)",
    nameEn: "Hack squat (machine)",
    category: "ben",
    primaryMuscles: ["forlaar", "balder"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Stil dig med ryggen mod puden og skuldrene under skulderpuderne.",
      "Placér fødderne skulderbredt lidt fremme på pladen.",
      "Løsn sikringen og sænk dig roligt til lårene er omtrent vandrette.",
      "Pres op igen gennem hælene — lås ikke knæene i toppen.",
    ],
    instructionsStepsEn: [
      "Stand with your back against the pad and your shoulders under the shoulder pads.",
      "Place your feet shoulder-width apart, slightly forward on the plate.",
      "Release the safety and lower calmly until your thighs are about horizontal.",
      "Press back up through your heels — do not lock your knees at the top.",
    ],
    cues: ["Hælene i pladen", "Knæ følger tæerne", "Ryggen bliver på puden"],
    cuesEn: ["Heels into the plate", "Knees track over your toes", "Back stays on the pad"],
    saferVariant: "Benpres i stedet hvis knæene eller lænden ikke er med.",
    saferVariantEn: "Use the leg press instead if your knees or lower back are not up for it.",
    svgKey: "hacksquat",
    difficulty: "erfaren",
  },
  {
    slug: "hofte-abduktion",
    nameDa: "Hofte-abduktion / udadføring (maskine)",
    nameEn: "Hip abduction (machine)",
    category: "ben",
    primaryMuscles: ["balder"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Sæt dig med ryggen mod ryglænet og knæene mod indersiden af puderne.",
      "Hold fast i håndtagene og ryggen i ro.",
      "Pres knæene udad så langt du kan uden at læne dig.",
      "Før roligt sammen igen uden at vægtene rammer stakken.",
    ],
    instructionsStepsEn: [
      "Sit with your back against the backrest and your knees against the inside of the pads.",
      "Hold the handles and keep your back still.",
      "Push your knees outward as far as you can without leaning.",
      "Bring them back together calmly without letting the weights touch the stack.",
    ],
    cues: ["Pres fra hoften, ikke fra knæet", "Overkroppen i ro", "Rolig retur"],
    cuesEn: ["Push from the hip, not the knee", "Upper body still", "Slow return"],
    saferVariant: "Mindre bevægebane hvis hoften klikker eller strammer.",
    saferVariantEn: "Reduce the range of motion if the hip clicks or tightens.",
    svgKey: "abduction",
    difficulty: "begynder",
  },
  {
    slug: "hofte-adduktion",
    nameDa: "Hofte-adduktion / indadføring (maskine)",
    nameEn: "Hip adduction (machine)",
    category: "ben",
    primaryMuscles: ["inderlaar"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Sæt dig med knæene mod ydersiden af puderne og benene åbne.",
      "Vælg en startbredde der giver et let stræk, ikke et voldsomt.",
      "Pres knæene sammen i en rolig bevægelse.",
      "Åbn kontrolleret igen til startpositionen.",
    ],
    instructionsStepsEn: [
      "Sit with your knees against the outside of the pads and your legs open.",
      "Pick a starting width that gives a light stretch, not a hard one.",
      "Press your knees together in one calm movement.",
      "Open back under control to the starting position.",
    ],
    cues: ["Klem i midten", "Ingen ryk", "Ryggen mod sædet"],
    cuesEn: ["Squeeze at the middle", "No jerking", "Back against the seat"],
    saferVariant: "Smallere start hvis lysken strammer.",
    saferVariantEn: "Start narrower if the groin feels tight.",
    svgKey: "adduction",
    difficulty: "begynder",
  },
  {
    slug: "laegpres",
    nameDa: "Lægpres / calf raise (maskine)",
    nameEn: "Calf raise (machine)",
    category: "ben",
    primaryMuscles: ["laeg"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Sæt forfoden på kanten af pladen så hælene hænger frit.",
      "Sænk hælene roligt til du mærker stræk i læggen.",
      "Pres op på tæerne så højt du kan.",
      "Hold et øjeblik i toppen og sænk igen med kontrol.",
    ],
    instructionsStepsEn: [
      "Place the balls of your feet on the edge of the plate so your heels hang free.",
      "Lower your heels calmly until you feel a stretch in the calf.",
      "Press up onto your toes as high as you can.",
      "Pause a moment at the top and lower again under control.",
    ],
    cues: ["Fuld bevægebane", "Hold i toppen", "Ingen hop"],
    cuesEn: ["Full range of motion", "Pause at the top", "No bouncing"],
    saferVariant: "Mindre stræk i bunden hvis akillessenen er øm.",
    saferVariantEn: "Less stretch at the bottom if the Achilles tendon is sore.",
    svgKey: "calf",
    difficulty: "begynder",
  },
  {
    slug: "rygstraek",
    nameDa: "Rygstræk / back extension (maskine)",
    nameEn: "Back extension (machine)",
    category: "kerne",
    primaryMuscles: ["ryg", "balder", "baglaar"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Justér sædet så rygpuden hviler mellem skulderbladene.",
      "Sæt fødderne fast og kryds armene over brystet.",
      "Pres roligt bagud mod puden til kroppen er lige.",
      "Før langsomt frem igen uden at runde ryggen helt.",
    ],
    instructionsStepsEn: [
      "Adjust the seat so the back pad rests between your shoulder blades.",
      "Plant your feet and cross your arms over your chest.",
      "Press back calmly against the pad until your body is straight.",
      "Return slowly without fully rounding your back.",
    ],
    cues: ["Lige — ikke længere", "Rolig i begge retninger", "Spænd balderne"],
    cuesEn: ["Straight — no further", "Calm both ways", "Squeeze your glutes"],
    saferVariant: "Let vægt og kort bevægebane ved lændegener; planken gør det samme arbejde uden belastning.",
    saferVariantEn: "Light weight and a short range if your lower back complains; the plank does the same job without load.",
    svgKey: "backext",
    difficulty: "begynder",
  },
  {
    slug: "mavemaskine",
    nameDa: "Mavebøjning (maskine)",
    nameEn: "Ab crunch (machine)",
    category: "kerne",
    primaryMuscles: ["mave"],
    equipment: "maskine",
    unit: "kg",
    isBodyweight: false,
    instructionsSteps: [
      "Sæt dig med brystet mod puden eller hænderne på håndtagene, alt efter maskinen.",
      "Sæt fødderne fast under puderne.",
      "Krøl overkroppen ned mod knæene — det er maven der bøjer, ikke armene der trækker.",
      "Før roligt op igen uden at slippe spændingen.",
    ],
    instructionsStepsEn: [
      "Sit with your chest against the pad or your hands on the handles, depending on the machine.",
      "Lock your feet under the pads.",
      "Curl your upper body down toward your knees — the abs bend, the arms do not pull.",
      "Return calmly without releasing the tension.",
    ],
    cues: ["Pust ud på vej ned", "Ryggen runder, hoften bliver", "Ingen træk med armene"],
    cuesEn: ["Breathe out on the way down", "The back rounds, the hips stay", "No pulling with the arms"],
    saferVariant: "Lavere vægt og kortere bevægebane ved nakke- eller lændegener.",
    saferVariantEn: "Less weight and a shorter range if your neck or lower back bothers you.",
    svgKey: "abmachine",
    difficulty: "begynder",
  },
  {
    slug: "kondi-loebebaand",
    nameDa: "Løbebånd (kondi)",
    nameEn: "Treadmill (cardio)",
    category: "kondi",
    primaryMuscles: ["ben", "kondi"],
    equipment: "maskine",
    unit: "km",
    isBodyweight: false,
    instructionsSteps: [
      "Start båndet i gang-tempo og sæt clipsen fast i tøjet.",
      "Øg farten trin for trin til det tempo du vil holde.",
      "Løb eller gå midt på båndet med blikket fremad.",
      "Sæt farten ned et minut før du stopper.",
    ],
    instructionsStepsEn: [
      "Start the belt at walking pace and clip the safety cord to your clothes.",
      "Raise the speed step by step to the pace you want to hold.",
      "Run or walk in the middle of the belt, eyes forward.",
      "Slow down for a minute before you stop.",
    ],
    cues: ["Slip håndtagene", "Korte, lette skridt", "Træk vejret roligt"],
    cuesEn: ["Let go of the handrails", "Short, light steps", "Breathe calmly"],
    saferVariant: "Rask gang med hældning i stedet for løb hvis knæene generer.",
    saferVariantEn: "Brisk walking on an incline instead of running if your knees complain.",
    svgKey: "treadmill",
    difficulty: "begynder",
  },
  {
    slug: "kondi-crosstrainer",
    nameDa: "Crosstrainer (kondi)",
    nameEn: "Elliptical (cardio)",
    category: "kondi",
    primaryMuscles: ["ben", "kondi"],
    equipment: "maskine",
    unit: "km",
    isBodyweight: false,
    instructionsSteps: [
      "Stil dig med hele foden på pedalerne og grib de bevægelige håndtag.",
      "Vælg en modstand du kan holde jævnt.",
      "Træd i en rolig, rund bevægelse og lad armene følge med.",
      "Hold overkroppen oprejst — læn dig ikke frem over håndtagene.",
    ],
    instructionsStepsEn: [
      "Stand with your whole foot on the pedals and hold the moving handles.",
      "Pick a resistance you can hold steadily.",
      "Stride in a calm, round motion and let your arms follow.",
      "Keep your upper body upright — do not lean over the handles.",
    ],
    cues: ["Hælene bliver på pedalerne", "Jævn rytme", "Skuldre afslappede"],
    cuesEn: ["Heels stay on the pedals", "Steady rhythm", "Relaxed shoulders"],
    saferVariant: "Det er det skånsomme valg for knæ og hofter — sænk modstanden hvis det stadig generer.",
    saferVariantEn: "This is the gentle choice for knees and hips — lower the resistance if it still bothers you.",
    svgKey: "elliptical",
    difficulty: "begynder",
  },
];

// ---- Workout templates ---------------------------------------------------

export interface SeedTemplateExercise {
  slug: string;
  targetSets: number;
  targetRepsMin?: number;
  targetRepsMax?: number;
  targetSeconds?: number;
  restSeconds: number;
  progressionMode?: ProgressionMode;
}

export interface SeedTemplate {
  name: string;
  nameEn: string;
  description: string;
  descriptionEn: string;
  goal: WorkoutGoal;
  level: Difficulty;
  estimatedMinutes: number;
  exercises: SeedTemplateExercise[];
}

const R = (sets: number, min: number, max: number, rest = 90): SeedTemplateExercise => ({
  slug: "",
  targetSets: sets,
  targetRepsMin: min,
  targetRepsMax: max,
  restSeconds: rest,
});
const withSlug = (slug: string, base: SeedTemplateExercise): SeedTemplateExercise => ({
  ...base,
  slug,
});

export const SEED_TEMPLATES: SeedTemplate[] = [
  {
    name: "Startprogram – Helkrop",
    nameEn: "Starter Programme – Full Body",
    description: "Kristian & Ibs syv-øvelsers startprogram. Hele kroppen, roligt tempo.",
    descriptionEn: "Kristian & Ib's seven-exercise starter programme. Whole body, calm pace.",
    goal: "helkrop",
    level: "begynder",
    estimatedMinutes: 50,
    exercises: [
      withSlug("benpres", R(3, 10, 12)),
      withSlug("brystpres", R(3, 10, 12)),
      withSlug("siddende-roning", R(3, 10, 12)),
      withSlug("nedtraek", R(3, 10, 12)),
      withSlug("skulderpres", R(3, 10, 12)),
      withSlug("leg-curl", R(3, 10, 12)),
      { slug: "planke", targetSets: 3, targetSeconds: 30, restSeconds: 45 },
    ],
  },
  {
    name: "Helkrop A",
    nameEn: "Full Body A",
    description: "Variant A i et A/B-split. Fokus på pres og forben.",
    descriptionEn: "Variant A of an A/B split. Focus on pushing and quads.",
    goal: "helkrop",
    level: "begynder",
    estimatedMinutes: 45,
    exercises: [
      withSlug("benpres", R(3, 10, 12)),
      withSlug("brystpres", R(3, 10, 12)),
      withSlug("nedtraek", R(3, 10, 12)),
      withSlug("skulderpres", R(3, 10, 12)),
      { slug: "planke", targetSets: 3, targetSeconds: 30, restSeconds: 45 },
    ],
  },
  {
    name: "Helkrop B",
    nameEn: "Full Body B",
    description: "Variant B i et A/B-split. Fokus på træk og baglår.",
    descriptionEn: "Variant B of an A/B split. Focus on pulling and hamstrings.",
    goal: "helkrop",
    level: "begynder",
    estimatedMinutes: 45,
    exercises: [
      withSlug("leg-curl", R(3, 10, 12)),
      withSlug("siddende-roning", R(3, 10, 12)),
      withSlug("goblet-squat", R(3, 8, 12)),
      withSlug("biceps-curl", R(3, 10, 15)),
      withSlug("triceps-pushdown", R(3, 10, 15)),
    ],
  },
  {
    name: "Kort 20-min",
    nameEn: "Short 20-min",
    description: "Presset tid? Fire øvelser, ind og ud på 20 minutter.",
    descriptionEn: "Short on time? Four exercises, in and out in 20 minutes.",
    goal: "helkrop",
    level: "begynder",
    estimatedMinutes: 20,
    exercises: [
      withSlug("benpres", R(2, 10, 12, 60)),
      withSlug("brystpres", R(2, 10, 12, 60)),
      withSlug("siddende-roning", R(2, 10, 12, 60)),
      { slug: "planke", targetSets: 2, targetSeconds: 30, restSeconds: 45 },
    ],
  },
  {
    name: "Kun overkrop",
    nameEn: "Upper Body Only",
    description: "Overkropsdag: bryst, ryg, skuldre og arme.",
    descriptionEn: "Upper body day: chest, back, shoulders and arms.",
    goal: "split",
    level: "begynder",
    estimatedMinutes: 45,
    exercises: [
      withSlug("brystpres", R(3, 10, 12)),
      withSlug("nedtraek", R(3, 10, 12)),
      withSlug("skulderpres", R(3, 10, 12)),
      withSlug("siddende-roning", R(3, 10, 12)),
      withSlug("biceps-curl", R(2, 10, 15, 60)),
      withSlug("triceps-pushdown", R(2, 10, 15, 60)),
    ],
  },
  {
    name: "Kun ben",
    nameEn: "Legs Only",
    description: "Bendag: forben, baglår og balder.",
    descriptionEn: "Leg day: quads, hamstrings and glutes.",
    goal: "split",
    level: "begynder",
    estimatedMinutes: 40,
    exercises: [
      withSlug("benpres", R(3, 10, 12)),
      withSlug("leg-curl", R(3, 10, 12)),
      withSlug("goblet-squat", R(3, 8, 12)),
      withSlug("rumaensk-markloeft-maskine", R(3, 10, 12)),
    ],
  },
  {
    name: "Kondi + kerne",
    nameEn: "Cardio + Core",
    description: "Rolig kondition og en stærk mave. God aktiv restitution.",
    descriptionEn: "Easy cardio and a strong core. Good active recovery.",
    goal: "kondi",
    level: "begynder",
    estimatedMinutes: 30,
    exercises: [
      { slug: "kondi-romaskine", targetSets: 1, restSeconds: 60, progressionMode: "none" },
      { slug: "planke", targetSets: 3, targetSeconds: 30, restSeconds: 45 },
      withSlug("mavehaevninger", R(3, 12, 20, 45)),
    ],
  },
];

// ---- Badges (runes) ------------------------------------------------------

export interface SeedBadge {
  slug: string;
  name: string;
  description: string;
  runeSymbol: string;
  tier: "bronze" | "soelv" | "guld";
  criteriaJson: Record<string, unknown>;
}

export const SEED_BADGES: SeedBadge[] = [
  { slug: "foerste-traening", name: "Første skridt", description: "Din allerførste træning er logget.", runeSymbol: "ᚠ", tier: "bronze", criteriaJson: { type: "sessions", count: 1 } },
  { slug: "ti-traeninger", name: "Ti gange rejst", description: "10 træninger gennemført.", runeSymbol: "ᚦ", tier: "bronze", criteriaJson: { type: "sessions", count: 10 } },
  { slug: "halvtreds-traeninger", name: "Hærdet", description: "50 træninger gennemført.", runeSymbol: "ᚨ", tier: "soelv", criteriaJson: { type: "sessions", count: 50 } },
  { slug: "hundrede-traeninger", name: "Hundrede vintre", description: "100 træninger gennemført.", runeSymbol: "ᚱ", tier: "guld", criteriaJson: { type: "sessions", count: 100 } },
  { slug: "foerste-pr", name: "Første rekord", description: "Du har slået din første personlige rekord.", runeSymbol: "ᚲ", tier: "bronze", criteriaJson: { type: "pr", count: 1 } },
  { slug: "fem-ugers-stime", name: "Ubrudt stime", description: "5 uger i træk med træning.", runeSymbol: "ᚷ", tier: "soelv", criteriaJson: { type: "week_streak", count: 5 } },
  { slug: "tidlig-fugl", name: "Før ravnene", description: "Trænede før kl. 7 om morgenen.", runeSymbol: "ᚹ", tier: "bronze", criteriaJson: { type: "before_hour", hour: 7 } },
  { slug: "hele-biblioteket", name: "Alt prøvet", description: "Du har prøvet hver øvelse i biblioteket.", runeSymbol: "ᚺ", tier: "guld", criteriaJson: { type: "all_exercises" } },
];
